import effects from "./effects";

export default {
    slash: {
        radius: 16,
        dimX: 24,
        dimY: 32,
        speed: 0,
        name: "slash",
        animation: "slash",
        type: "attack",
        delay: 1,
        duration: 5,
        collideHealth: 1,
        bounce: 0,
        effect: effects.bleed,
        selfTarget: false,
    },
    fireball: {
        radius: 12,
        dimX: 64,
        dimY: 32,
        speed: 25,
        cooldown: 25,
        name: "fireball",
        animation: "fireball",
        type: "attack",
        delay: 1,
        duration: 1000,
        collideHealth: 0,
        bounce: 0.5,
        effect: effects.ignited,
        selfTarget: false,
    },
    bloodOrb: {
        radius: 8,
        dimX: 32,
        dimY: 32,
        speed: 125,
        cooldown: 25,
        name: "bloodOrb",
        animation: "bloodOrb",
        particles: "bloodOrbParticles_particles",
        type: "attack",
        delay: 1,
        duration: 1000,
        collideHealth: 5,
        bounce: 1,
        effect: effects.drained,
        selfTarget: false,
    },
    poisonOrb: {
        radius: 8,
        dimX: 32,
        dimY: 32,
        speed: 75,
        cooldown: 25,
        name: "poisonOrb",
        animation: "poisonOrb",
        particles: "poisonOrbParticles_particles",
        particlesSheet: "poisonOrbParticles",
        type: "attack",
        delay: 1,
        duration: 1000,
        collideHealth: 0,
        bounce: 1,
        effect: effects.poisoned,
        selfTarget: false,
        explodes: true,
        explodeRadius: 32,
    },
    iceOrb: {
        radius: 45,
        dimX: 32,
        dimY: 32,
        speed: 200,
        cooldown: 25,
        name: "iceOrb",
        animation: "iceOrb",
        particles: "iceOrbParticles_particles",
        particlesSheet: "iceOrbParticles",
        type: "attack",
        delay: 1,
        duration: 1000,
        collideHealth: 0,
        bounce: 1,
        effect: effects.chilled,
        selfTarget: false,
        explodes: true,
        explodeRadius: 32,
    },
};