export default {
    iceOrb: function(gameObject) {
        return {
        flightParticle: [0],
        explosionParticle: [1, 2],
        afterParticle: [0],
        flight: {
            // alpha: { start: 1, end: 0.5, ease: 'Expo.easeOut' },
            quantity: 1,
            frequency: 200,
            angle: { min: 0, max: 360 },
            // alpha: { min: 0, max: 1 },
            speed: 20,
            // gravityY: 100,
            lifespan: { min: 1500, max: 2000 },
            follow: gameObject,
            // blendMode: 'SCREEN',
            // scale: 0.25,
        },
        explosion: {
            // alpha: { start: 1, end: 0.1, ease: 'Expo.easeOut' },
            quantity: 15,
            frequency: 1,
            angle: { min: 0, max: 360 },
            speed: { min: 150, max: 200},
            lifespan: { min: 1600, max: 2000 },
            gravityY: 0,
            follow: gameObject,
            // blendMode: 'ADD',
            // emitZone: { type: 'random', source: new Phaser.Geom.Circle(0, 0, 4) },
            // deathZone: { type: 'onLeave', source: new Phaser.Geom.Circle(gameObject?.x, gameObject?.y, 48) },
            maxParticles: 15,
        },
        after: {
            // alpha: { start: 1, end: 0.4, ease: 'Expo.easeOut' },
            quantity: 1,
            frequency: 200,
            angle: { min: 0, max: 360 },
            speed: 30,
            lifespan: { min: 2400, max: 3000 },
            follow: gameObject,
            // blendMode: 'ADD',
            // emitZone: { type: 'random', source: new Phaser.Geom.Circle(0, 0, 32) },
            // deathZone: { type: 'onLeave', source: new Phaser.Geom.Circle(gameObject?.x, gameObject?.y, 48) },
            maxParticles: 0,
        },
    }},
};