import effects from "./effects";

export default {
    dagger: {
        name: "dagger",
        attackCooldown: 0,
        action: {
            radius: 16,
            dimX: 24,
            dimY: 32,
            speed: 0,
            name: "slash",
            animation: "slash",
            type: "attack",
            delay: 1,
            duration: 5,
            collideHealth: 1,
            bounce: 0,
            effect: effects["5be01cde-0016-11ed-b939-0242ac120002"],
            selfTarget: false,
        },
    },
    fireballScroll: {
        name: "fireballScroll",
        attackCooldown: 0,
        action: {
            radius: 12,
            dimX: 64,
            dimY: 32,
            speed: 25,
            cooldown: 25,
            name: "fireball",
            animation: "fireball",
            type: "attack",
            delay: 1,
            duration: 1000,
            collideHealth: 0,
            bounce: 0.5,
            effect: effects["2c8c6620-0707-11ed-b939-0242ac120002"],
            selfTarget: false,
        },
    }, 
    bloodOrbScroll: {
        name: "bloodOrbScroll",
        attackCooldown: 0,
        action: {
            radius: 8,
            dimX: 32,
            dimY: 32,
            speed: 125,
            cooldown: 25,
            name: "bloodOrb",
            animation: "bloodOrb",
            particles: "bloodOrbParticles_particles",
            type: "attack",
            delay: 1,
            duration: 1000,
            collideHealth: 5,
            bounce: 1,
            effect: effects["3c8c6620-0707-11ed-b939-0242ac120002"],
            selfTarget: false,
        },
    },
    poisonOrbScroll: {
        name: "poisonOrbScroll",
        attackCooldown: 0,
        action: {
            radius: 8,
            dimX: 32,
            dimY: 32,
            speed: 75,
            cooldown: 25,
            name: "poisonOrb",
            animation: "poisonOrb",
            particles: "poisonOrbParticles_particles",
            particlesSheet: "poisonOrbParticles",
            type: "attack",
            delay: 1,
            duration: 1000,
            collideHealth: 0,
            bounce: 1,
            effect: effects["4c8c6620-0707-11ed-b939-0242ac120002"],
            selfTarget: false,
            explodes: true,
            explodeRadius: 32,
        },
    },
    iceOrbScroll: {
        name: "iceOrbScroll",
        attackCooldown: 0,
        action: {
            radius: 45,
            dimX: 32,
            dimY: 32,
            speed: 200,
            cooldown: 25,
            name: "iceOrb",
            animation: "iceOrb",
            particles: "iceOrbParticles_particles",
            particlesSheet: "iceOrbParticles",
            type: "attack",
            delay: 1,
            duration: 1000,
            collideHealth: 0,
            bounce: 1,
            effect: effects["4c8c6620-0707-11ed-b939-0242ac120002"],
            selfTarget: false,
            explodes: true,
            explodeRadius: 32,
        },
    },
}