import effects from "./effects";
import attacks from "./attacks";

export default {
    dagger: {
        name: "dagger",
        type: "melee",
        attackCooldown: 0,
        action: attacks.slash,
        healthCost: 0,
        manaCost: 0,
        staminaCost: 20,
    },
    bow: {
        name: "bow",
        type: "ranged",
        attackCooldown: 10,
        action: attacks.arrow,
        healthCost: 0,
        manaCost: 0,
        staminaCost: 10,
    },
    sabotageKitPoison: {
        name: "sabotageKitPoison",
        type: "deployable",
        attackCooldown: 50,
        action: attacks.poisonOrb,
        healthCost: 0,
        manaCost: 70,
        staminaCost: 10,
    },
    vampireBite: {
        name: "vampireBite",
        type: "melee",
        attackCooldown: 0,
        action: attacks.vampireBite,
        healthCost: 0,
        manaCost: 0,
        staminaCost: 100,
    },
    fireballScroll: {
        name: "fireballScroll",
        attackCooldown: 0,
        action: attacks.fireball,
        healthCost: 0,
        manaCost: 0,
        staminaCost: 20,
    }, 
    bloodOrbScroll: {
        name: "bloodOrbScroll",
        attackCooldown: 30,
        action: attacks.bloodOrb,
        healthCost: 5,
        manaCost: 0,
        staminaCost: 0,
    },
    poisonOrbScroll: {
        name: "poisonOrbScroll",
        attackCooldown: 0,
        action: attacks.poisonOrb,
        healthCost: 0,
        manaCost: 20,
        staminaCost: 0,
    },
    iceOrbScroll: {
        name: "iceOrbScroll",
        attackCooldown: 0,
        action: attacks.iceOrb,
        healthCost: 0,
        manaCost: 40,
        staminaCost: 0,
    },
}